language: objective-c
env:
  - RVM_RUBY_VERSION=2.0 NOEXEC_DISABLE=1 CI=true
before_install: source ~/.rvm/scripts/rvm && rvm use $RVM_RUBY_VERSION
install: sudo gem install bundler --no-ri --no-rdoc && bundle install --without=documentation
script: bundle exec rake spec
