language: objective-c
env:
  - RVM_RUBY_VERSION=system NOEXEC_DISABLE=1 CI=true RUBY_VERSION_SPECIFIC='sudo gem update --system && sudo gem install bundler --no-ri --no-rdoc'
before_install: source ~/.rvm/scripts/rvm && rvm use $RVM_RUBY_VERSION
script: bundle exec rake spec